export const speakers = [
    // {
    //     id: 1,
    //     fullName: 'V Ananth Nageswaran',
    //     des: 'Chief Economic Advisor for India',
    //     profileimage: '',
    // },
    {
        id: 2,
        fullName: 'Vineeta Hariharan',
        des: 'Senior Leader, World Bank & Public Policy',
        profileimage: '/images/speakers/Vineeta-Hariharan.JPG',
    },
    {
        id: 7,
        fullName: 'Dr Shiv Mohan',
        des: 'Sr Director, Chandrayaan 1, Distinguished Career Scientist, ISRO',
        profileimage: '/images/speakers/Shiv-Mohan.jpg',
    },
    {
        id: 3,
        fullName: 'Dr Vijender Singh Chauhan',
        des: 'UPSC expert, Associate Professor, DU',
        profileimage: '/images/speakers/Vijender-Chauhan.JPG',
    },
    {
        id: 4,
        fullName: 'Dr Pawan Kumar Singh',
        des: 'Director, IIM Trichy',
        profileimage: '/images/speakers/Pawan-Kumar-Singh.jpg',
    },
    {
        id: 5,
        fullName: 'Shuchi Sinha',
        des: 'Behavioural Scientist & Professor, IIT Delhi',
        profileimage: '/images/speakers/Shuchi-Sinha.JPG',
    },
    // {
    //     id: 6,
    //     fullName: 'Dr Arushi Malik',
    //     des: 'Divisional Commissioner, Jaipur',
    //     profileimage: '',
    // },
    {
        id: 8,
        fullName: 'Siddharth Rajhans',
        des: 'Career Diplomat, UN | Economic Diplomacy',
        profileimage: '/images/speakers/Siddharth-Rajhans.JPG',
    },
    // {
    //     id: 9,
    //     fullName: 'Chef Thiru',
    //     des: 'Principal, WGSHA, MAHE, Sustainability in Hospitality',
    //     profileimage: '',
    // },
    // {
    //     id: 10,
    //     fullName: 'Aravind Chinchure',
    //     des: 'Founder and CEO of QLeap Academy',
    //     profileimage: '',
    // },
    {
        id: 11,
        fullName: 'Monika Singh',
        des: 'Sustainability expert in Aviation, IndiGo',
        profileimage: '/images/speakers/Monika-Singh.jpg',
    },
    {
        id: 12,
        fullName: 'Shilpa Mehta',
        des: 'Director of PwC India',
        profileimage: '/images/speakers/Shilpa-Mehta.JPG',
    },
    // {
    //     id: 13,
    //     fullName: 'Dr Prayatna Jain',
    //     des: 'Marketing & Economics, PIMR, Indore',
    //     profileimage: '',
    // },
    {
        id: 14,
        fullName: 'Dr Jayashree Periwal',
        des: 'Chairperson, Jayashree Periwal Group of Institutions',
        profileimage: '/images/speakers/Jayshree-Periwal.jpg',
    },
    {
        id: 15,
        fullName: 'Dr Ajit Upadhyay',
        des: 'Director, PIMR Indore',
        profileimage: '/images/speakers/Ajit-Upadhyay.JPG',
    },
];